const http=require('http');
const {URL}=require('url');
const proj4=require('proj4');
const PORT=process.env.PORT||10000;
const WFS='https://mapy.geoportal.gov.pl/wss/service/PZGIK/EGIB/WFS/UslugaZbiorcza';
const CRS2180='+proj=tmerc +lat_0=0 +lon_0=19 +k=0.9993 +x_0=500000 +y_0=-5300000 +ellps=GRS80 +units=m +no_defs +type=crs';
proj4.defs('EPSG:2180',CRS2180);
function send(res,status,type,body){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS'});res.end(body)}
function bbox2180(bbox){const p=String(bbox||'').split(',').slice(0,4).map(Number);if(p.length!==4||p.some(v=>!Number.isFinite(v)))return null;const [south,west,north,east]=p;const corners=[[west,south],[east,south],[east,north],[west,north]].map(ll=>proj4('EPSG:4326','EPSG:2180',ll));const xs=corners.map(p=>p[0]),ys=corners.map(p=>p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
async function wfs(reqUrl,res){const u=new URL(reqUrl,'http://localhost');const b=bbox2180(u.searchParams.get('bbox'));if(!b)return send(res,400,'application/json; charset=utf-8',JSON.stringify({error:'Nieprawidłowy bbox EPSG:4326.'}));const filter=`<fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2"><fes:BBOX><fes:ValueReference>geom</fes:ValueReference><gml:Envelope srsName="EPSG:2180"><gml:lowerCorner>${b.minX.toFixed(2)} ${b.minY.toFixed(2)}</gml:lowerCorner><gml:upperCorner>${b.maxX.toFixed(2)} ${b.maxY.toFixed(2)}</gml:upperCorner></gml:Envelope></fes:BBOX></fes:Filter>`;const target=new URL(WFS);for(const[k,v]of Object.entries({service:'WFS',version:'2.0.0',request:'GetFeature',typenames:'ms:dzialki',srsName:'EPSG:4326',filter,startIndex:'0',count:'2000',propertyName:'id_dzialki,geom'}))target.searchParams.set(k,v);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),170000);try{const r=await fetch(target.href,{signal:controller.signal,headers:{'User-Agent':'MAPA production parcel labels/1.0','Accept':'application/json,text/json,*/*'}});const text=await r.text();clearTimeout(timer);const ct=(r.headers.get('content-type')||'').toLowerCase();if(ct.includes('json'))return send(res,r.status,'application/json; charset=utf-8',text);return send(res,502,'application/json; charset=utf-8',JSON.stringify({error:'WFS nie zwrócił GeoJSON.',contentType:ct,preview:text.slice(0,300)}))}catch(e){clearTimeout(timer);return send(res,502,'application/json; charset=utf-8',JSON.stringify({error:e.name==='AbortError'?'GUGiK WFS przekroczył limit 170 s.':e.message}))}}
const server=http.createServer((req,res)=>{if(req.method==='OPTIONS')return send(res,204,'text/plain','');try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health')return send(res,200,'application/json; charset=utf-8',JSON.stringify({ok:true,service:'MAPA production parcel labels API'}));if(u.pathname==='/api/wfs')return wfs(req.url,res);return send(res,404,'application/json; charset=utf-8',JSON.stringify({error:'Not found'}))}catch(e){return send(res,500,'application/json; charset=utf-8',JSON.stringify({error:e.message}))}});
server.listen(PORT,'0.0.0.0',()=>console.log('MAPA production parcel labels API listening on '+PORT));