const http=require('http');
const {URL}=require('url');
const proj4=require('proj4');
const PORT=process.env.PORT||10000;
const WFS='https://mapy.geoportal.gov.pl/wss/service/PZGIK/EGIB/WFS/UslugaZbiorcza';
const CRS2180='+proj=tmerc +lat_0=0 +lon_0=19 +k=0.9993 +x_0=500000 +y_0=-5300000 +ellps=GRS80 +units=m +no_defs +type=crs';
proj4.defs('EPSG:2180',CRS2180);
function send(res,status,type,body){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,OPTIONS'});res.end(body)}
function bbox2180(bbox){const p=String(bbox||'').split(',').slice(0,4).map(Number);if(p.length!==4||p.some(v=>!Number.isFinite(v)))return null;const [south,west,north,east]=p;const corners=[[west,south],[east,south],[east,north],[west,north]].map(ll=>proj4('EPSG:4326','EPSG:2180',ll));const xs=corners.map(p=>p[0]),ys=corners.map(p=>p[1]);return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)}}
function xmlDecode(s){return String(s||'').replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").trim()}
function ringFromPosList(s){const n=String(s||'').trim().split(/\s+/).map(Number);if(n.length<8||n.length%2)return null;const out=[];for(let i=0;i<n.length;i+=2){if(!Number.isFinite(n[i])||!Number.isFinite(n[i+1]))return null;const y=n[i],x=n[i+1],p=proj4('EPSG:2180','EPSG:4326',[x,y]);out.push([p[0],p[1]])}return out}
function parseGml(text){const features=[];const members=text.match(/<wfs:member\b[\s\S]*?<\/wfs:member>/gi)||[];for(const member of members){const idm=member.match(/<ms:id_dzialki\b[^>]*>([\s\S]*?)<\/ms:id_dzialki>/i);const id=xmlDecode(idm&&idm[1]);if(!id)continue;const rings=[];const re=/<gml:(?:exterior|interior)\b[\s\S]*?<gml:posList\b[^>]*>([\s\S]*?)<\/gml:posList>[\s\S]*?<\/gml:(?:exterior|interior)>/gi;let m;while((m=re.exec(member))){const ring=ringFromPosList(m[1]);if(ring)rings.push(ring)}if(!rings.length)continue;features.push({type:'Feature',properties:{id_dzialki:id},geometry:{type:'Polygon',coordinates:rings}})}return{type:'FeatureCollection',features}}
function normalizeJsonGeoJson(data){if(!data||!Array.isArray(data.features))return null;let transformed=0;function walk(v){if(!Array.isArray(v))return v;if(v.length>=2&&typeof v[0]==='number'&&typeof v[1]==='number'){const x=v[0],y=v[1];if(Math.abs(x)>180||Math.abs(y)>90){const p=proj4('EPSG:2180','EPSG:4326',[x,y]);transformed++;return[p[0],p[1],...v.slice(2)]}return v}return v.map(walk)}const out=JSON.parse(JSON.stringify(data));for(const f of out.features){if(f&&f.geometry&&f.geometry.coordinates)f.geometry.coordinates=walk(f.geometry.coordinates)}console.log('WFS_JSON_NORMALIZED',JSON.stringify({features:out.features.length,transformedCoordinates:transformed,sampleId:out.features[0]?.properties?.id_dzialki||out.features[0]?.properties?.idDzialki||null,sampleGeometry:out.features[0]?.geometry?.type||null,sampleCoordinate:out.features[0]?.geometry?.coordinates?.[0]?.[0]||null}));return out}
async function wfs(reqUrl,res){const u=new URL(reqUrl,'http://localhost');const b=bbox2180(u.searchParams.get('bbox'));if(!b)return send(res,400,'application/json; charset=utf-8',JSON.stringify({error:'Nieprawidłowy bbox EPSG:4326.'}));const filter=`<fes:Filter xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2"><fes:BBOX><fes:ValueReference>geom</fes:ValueReference><gml:Envelope srsName="EPSG:2180"><gml:lowerCorner>${b.minY.toFixed(2)} ${b.minX.toFixed(2)}</gml:lowerCorner><gml:upperCorner>${b.maxY.toFixed(2)} ${b.maxX.toFixed(2)}</gml:upperCorner></gml:Envelope></fes:BBOX></fes:Filter>`;console.log('WFS_BBOX_2180',JSON.stringify({minX:b.minX,maxX:b.maxX,minY:b.minY,maxY:b.maxY,axisOrder:'Y X'}));const target=new URL(WFS);for(const[k,v]of Object.entries({service:'WFS',version:'2.0.0',request:'GetFeature',typenames:'ms:dzialki',srsName:'EPSG:2180',filter,startIndex:'0',count:'1000',propertyName:'id_dzialki,geom'}))target.searchParams.set(k,v);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),170000);try{const r=await fetch(target.href,{signal:controller.signal,headers:{'User-Agent':'MAPA production parcel labels/2.2','Accept':'application/json,text/json,application/xml,text/xml,*/*'}});const text=await r.text();clearTimeout(timer);const ct=(r.headers.get('content-type')||'').toLowerCase();if(ct.includes('json')){try{const data=normalizeJsonGeoJson(JSON.parse(text));if(data)return send(res,r.status,'application/json; charset=utf-8',JSON.stringify(data))}catch(e){console.error('WFS_JSON_PARSE_ERROR',e.message)}return send(res,r.status,'application/json; charset=utf-8',text)}if(r.ok&&/<(?:wfs:)?FeatureCollection\b/i.test(text)){const data=parseGml(text);console.log('WFS_GML_PARSED',JSON.stringify({features:data.features.length,sampleId:data.features[0]?.properties?.id_dzialki||null,sampleGeometry:data.features[0]?.geometry?.type||null,sampleCoordinate:data.features[0]?.geometry?.coordinates?.[0]?.[0]||null}));return send(res,200,'application/json; charset=utf-8',JSON.stringify(data))}return send(res,502,'application/json; charset=utf-8',JSON.stringify({error:'WFS nie zwrócił danych GeoJSON/GML.',status:r.status,contentType:ct,preview:text.slice(0,500)}))}catch(e){clearTimeout(timer);return send(res,502,'application/json; charset=utf-8',JSON.stringify({error:e.name==='AbortError'?'GUGiK WFS przekroczył limit 170 s.':e.message}))}}
const server=http.createServer((req,res)=>{if(req.method==='OPTIONS')return send(res,204,'text/plain','');try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health')return send(res,200,'application/json; charset=utf-8',JSON.stringify({ok:true,service:'MAPA production parcel labels API',format:'GeoJSON',outputCrs:'EPSG:4326'}));if(u.pathname==='/api/wfs')return wfs(req.url,res);return send(res,404,'application/json; charset=utf-8',JSON.stringify({error:'Not found'}))}catch(e){return send(res,500,'application/json; charset=utf-8',JSON.stringify({error:e.message}))}});
server.listen(PORT,'0.0.0.0',()=>console.log('MAPA production parcel labels API listening on '+PORT));